name: heterosketch
channels:
  - gurobi
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - anyqt=0.0.10
  - argon2-cffi=20.1.0
  - astroid=2.3.3
  - async_generator=1.10
  - attrs=20.3.0
  - autoflake=1.3
  - autopep8=1.4.4
  - backcall=0.2.0
  - beautifulsoup4=4.9.0
  - bibtexparser=1.1.0
  - blas=1.0
  - bleach=3.3.0
  - bottleneck=1.3.2
  - brotlipy=0.7.0
  - ca-certificates=2021.1.19
  - cachecontrol=0.12.6
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=3.0.4
  - click=7.1.1
  - cloudpickle=1.6.0
  - commonmark=0.9.1
  - cryptography=3.3.1
  - cycler=0.10.0
  - cython=0.29.21
  - dbus=1.13.18
  - decorator=4.4.2
  - defusedxml=0.6.0
  - dictdiffer=0.8.0
  - dill=0.3.3
  - docutils=0.16
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - expat=2.2.10
  - flake8=3.7.9
  - fontconfig=2.13.1
  - freetype=2.10.4
  - future=0.18.2
  - glib=2.67.4
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - gurobi=9.1.1
  - hdbscan=0.8.26
  - icu=58.2
  - idna=2.10
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - intel-openmp=2020.2
  - ipdb=0.12.3
  - ipykernel=5.3.4
  - ipython=7.11.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - isort=4.3.21
  - jdcal=1.4.1
  - jedi=0.15.2
  - jeepney=0.6.0
  - jinja2=2.11.3
  - joblib=1.0.1
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - keyring=22.3.0
  - keyrings.alt=4.0.2
  - kiwisolver=1.3.1
  - latexcodec=2.0.0
  - lazy-object-proxy=1.5.2
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - liblapack=3.8.0
  - libllvm10=10.0.1
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.10
  - llvmlite=0.34.0
  - lockfile=0.12.2
  - loky=2.7.0
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - more-itertools=8.7.0
  - msgpack-python=1.0.2
  - multiprocess=0.70.9
  - mypy=0.740
  - mypy_extensions=0.4.3
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - networkx=2.5
  - notebook=6.2.0
  - numba=0.51.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - openpyxl=3.0.6
  - openssl=1.1.1j
  - opentsne=0.4.3
  - orange-canvas-core=0.1.15
  - orange-widget-base=4.7.0
  - orange3=3.24.1
  - orange3-network=1.5.0
  - orderedset=2.0.3
  - packaging=20.9
  - palettable=3.3.0
  - pandas=1.2.3
  - pandoc=2.11
  - pandocfilters=1.4.3
  - parso=0.8.1
  - pathos=0.2.5
  - patsy=0.5.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.0.2
  - pluggy=0.13.1
  - pox=0.2.7
  - ppft=1.6.6.1
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.8
  - prompt_toolkit=3.0.8
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - py=1.10.0
  - pyamg=4.0.0
  - pybtex=0.22.2
  - pycodestyle=2.5.0
  - pycparser=2.20
  - pydocstyle=5.1.1
  - pyflakes=2.1.1
  - pygments=2.8.0
  - pylint=2.4.4
  - pynndescent=0.4.8
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyqtgraph=0.10.0
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - pytest=5.4.1
  - python=3.7.10
  - python-dateutil=2.8.1
  - python-jsonrpc-server=0.3.4
  - python-language-server=0.31.10
  - python-louvain=0.15
  - python_abi=3.7
  - pytz=2021.1
  - pyyaml=5.3.1
  - pyzmq=20.0.0
  - qt=5.9.7
  - qtconsole=5.0.2
  - qtpy=1.9.0
  - readline=8.1
  - requests=2.24.0
  - rope=0.18.0
  - scikit-learn=0.24.1
  - scikit-learn-extra=0.1.0b2
  - scipy=1.5.2
  - seaborn=0.10.0
  - secretstorage=3.3.1
  - send2trash=1.5.0
  - serverfiles=0.3.1
  - setuptools=52.0.0
  - sip=4.19.8
  - six=1.15.0
  - snowballstemmer=2.1.0
  - soupsieve=2.2
  - sqlite=3.33.0
  - statsmodels=0.12.0
  - tbb=2020.3
  - terminado=0.9.2
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tornado=6.1
  - traitlets=5.0.5
  - typed-ast=1.4.2
  - typing_extensions=3.7.4.3
  - ujson=1.35
  - urllib3=1.25.11
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - wrapt=1.12.1
  - xlrd=2.0.1
  - xlsxwriter=1.3.7
  - xz=5.2.5
  - yaml=0.1.7
  - yapf=0.30.0
  - zeromq=4.3.3
  - zipp=3.4.0
  - zlib=1.2.11

